# Site settings
title: jadynJT
SEOTitle: 敬填博客 | BY Blog
header-img: img/post-bg-rwd.jpg
email: 695331437@qq.com
description: "如果奇迹有颜色，那一定是红蓝色！"
keyword: "敬填博客, iOS, Apple, iPhone"
url: "https://jadynJT.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "BE THE BEST FOREVER"
sidebar-avatar: img/avatar-by.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    jadynJT
#facebook_username:  baiying.qiu.7
jianshu_username:   fa44c53e9937
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: jadynJT
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
#featured-tags: false                     # whether or not using Feature-Tags
#featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Vincent",
        href: "https://vincentcwlove.github.io/"
    },{
        title: "林茂佳",
        href: "https://linmaojia.github.io/"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
